_schema: _schema
source: /
paths:
  uploads: static/uploads
  uploads_use_relative_path: true
  static: static
collections_config:
  posts:
    path: _posts
    name: Posts
    icon: event_available
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_enabled_editors:
  - visual
commit_templates:
  - label:
    template_string:
    template_path:
    _inputs:
    extra_data:
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
editor:
  default_path: fightcancerdrc.org/editor
source_editor:
  tab_size: 2
  theme: cobalt
  show_gutter: true
timezone: Africa/Kinshasa
markdown:
  engine: commonmark
  options:
    xhtml: true
    breaks: true
    linkify: true
    typographer: true
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
