collections_config:
  posts:
    path: _posts
    name: Posts
    icon: event_available
paths:
  static: static
  uploads: static/uploads
timezone: Africa/Kinshasa
markdown:
  engine: commonmark
  options:
    gfm: true
    linkify: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    breaks: false
    xhtml: false
    attributes: false
    typographer: false
    treat_indentation_as_code: true
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
