backend:
  name: git-gateway
  branch: main  # Le nom de la branche de votre dépôt GitHub

media_folder: "static/images"  # Dossier où les images seront stockées
public_folder: "/images"  # L'emplacement public des images

collections:
  - name: "posts"  # Nom de la collection (ex : Articles)
    label: "Articles"
    folder: "_posts"  # Dossier où les articles seront stockés sous forme de fichiers Markdown
    create: true  # Permet de créer de nouveaux articles
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # Format du nom du fichier
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
