backend:
  name: github
  repo: Benedicto-m/fightcancerdrc
  branch: main
  auth_scope: repo
  client_id: Ov23lix2qO57DNu9MJ52

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "accueil_unique"
    label: "Page d'accueil"
    files:
      - file: "index.md"
        label: "Éditer page d'accueil"
        name: "accueil_file"
        fields:
          - label: "Titre"
            name: "title"
            widget: "string"
          - label: "Contenu"
            name: "body"
            widget: "markdown"

