backend:
  name: git-gateway
media_folder: "images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "posts"
    label: "Articles"
    folder: "posts"
    create: true
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Contenu", name: "body", widget: "markdown" }
