backend:
  name: github
  repo: Benedicto-m/fightcancerdrc. # Remplace par ton dépôt
  branch: main # Branche principale

media_folder: "images/uploads" # Où les images seront stockées
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Articles du Blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Titre", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Contenu", widget: "markdown" }
