backend:
  name: github
  repo: Benedicto-m/fightcancerdrc
  branch: main
  auth_scope: repo
  client_id: VOTRE_CLIENT_ID_GITHUB

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Accueil"
        name: "home"
        file: "index.md"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }
